language: rust
rust:
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose
