language: rust
rust:
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo +nightly clippy --all-targets --all-features -- -D warnings
  - cargo +nightly build --verbose
  - cargo +nightly test --verbose
  - cargo +nightly bench --verbose
  - cargo +nightly doc --verbose
