language: rust

matrix:
  include:
    - rust: stable
      before_script:
        - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      script:
        - cargo +stable build --verbose
        - cargo +stable doc
    - rust: nightly
      before_script:
        - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      script:
        - cargo +nightly build --verbose
        - cargo +nightly clippy --all-targets --all-features -- -D warnings
        - cargo +nightly test --verbose
        - cargo +nightly bench --verbose
