[package]
name = "jsondata"
version = "0.2.0"
authors = ["prataprc <prataprc@gmail.com>"]
description = "JSON processing package for document databses"
documentation = "https://docs.rs/jsondata"
homepage = "https://github.com/bnclabs/jsondata"
repository = "https://github.com/bnclabs/jsondata"
keywords = ["json", "json5"]
categories = ["encoding"]
license = "MIT"
exclude = ["template/**"]

[dependencies]
quickcheck = "0.7"
quickcheck_macros = "0.7"
lazy_static = "1.2.0"

[dev-dependencies]
quickcheck = "0.7"
quickcheck_macros = "0.7"

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "pest-parser/pest" }
